### ISSUE TITLE
Hi i have runing error after ./bootstrap.sh

### ISSUE THREAD

**Issue by kugimiya530** [fmira21/ton-node-docker#1]
can u help me and confirm where the problem is。

----------------------------------------------------------------------------------------
Creating ton_ton-node_1 ... error

ERROR: for ton_ton-node_1  Cannot start service ton-node: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/var/ton-work/db/init.sh": stat /var/ton-work/db/init.sh: no such file or directory: unknown

ERROR: for ton-node  Cannot start service ton-node: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/var/ton-work/db/init.sh": stat /var/ton-work/db/init.sh: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
unknown flag: --r
See 'docker run --help'.
Creating ton_ton-api_1 ... done

**Comment by sinaLong258** [comment]
+1

**Comment by redvoron** [comment]
+1

**Comment by fmira21** [comment]
@kugimiya530 @sinaLong258 @redvoron 
Just added multiple fixes to resolve this.
Can you check again?

Also, consider updating the version to 2023.11.

**Comment by redvoron** [comment]
@fmira21 Now it works!

Now it works! Thank you!
I'm waiting for this to disappear from the logs:
`[ 2][t 2][2023-12-25 15:42:04.055233109][manager-init.cpp:86][!downloadproofreq]        failed to download proof link: [Error : 651 : no nodes]`

**Comment by fmira21** [comment]
@redvoron 
Great!
Closing the issue.
If the node cannot find peers for long, please open a new one.
