### ISSUE TITLE
failed to load global config'/var/ton-work/db/ton-global.config

### ISSUE THREAD

**Issue by adapt7** [fmira21/ton-node-docker#2]
Docker container is restarting with error:

failed to load global config'/var/ton-work/db/ton-global.config

There is no way to access the container because it's restarting so cannot manually run the init.sh.

Any way to fix this somehow?

**Comment by fmira21** [comment]
Hi @adapt7 
Thank you for flagging!
`init.sh` downloads a global config file from `NODE_CONFIG_URL` as `/var/ton-work/db/ton-global.config`.
I will debug this flow. So far, you can download and rename this file manually. Then, move it to the external volume under `NODE_STATE_VOLUME` - it is assigned to `/var/ton-work/db/` inside the node container.

**Comment by adapt7** [comment]
@fmira21 I've updated db/ton-global.config, it was zero size. Now container still restarts with different error:

[ 1][t 1][2024-03-26 19:42:55.669657649][validator-engine.cpp:3543][!validator-engine]	failed to parse config: [Error : 0 : failed to parse json: Unexpected string end]

**Comment by fmira21** [comment]
@adapt7 Just check the config itself.
You can send your version here, if you wish.

**Comment by adapt7** [comment]
@fmira21 config file is correct JSON. How else can I debug this issue?

**Comment by fmira21** [comment]
@adapt7 Are you trying to use the Testnet one?
You can try Mainnet config as well. Also consider updating the node to 2024.03.

**Comment by adapt7** [comment]
@fmira21 already on mainnet and 2024.03.

**Comment by fmira21** [comment]
@adapt7 
Vice versa then, try testnet to make sure it's not a problem of the node.

**Comment by fmira21** [comment]
@adapt7 
https://ton.org/global-config.json
Is this the config you are using for Mainnet?

**Comment by adapt7** [comment]
@fmira21 correct, this is file I have in my host ./db/ton-global.config file.

**Comment by fmira21** [comment]
Hi @adapt7,
Is the issue resolved?

**Comment by adapt7** [comment]
Hi @fmira21 

Couldn't find solution so moved back to the no-docker full node installation.

If anyone however experience the same problem and will find the fix - please update everyone here.
