### ISSUE TITLE
getnextkey: [Error : 651 : not inited]

### ISSUE THREAD

**Issue by zhp1254** [fmira21/ton-node-docker#4]
i am not sure if my node is worked, beacuse it download 38454136 for a long time

[ 3][t 2][2024-06-19 13:50:58.930085703][adnl-peer.cpp:572][!peerpair][&ADNL_WARNING]   [peerpair 7usaIG7hiKKL215S7G+cUsXdlv+QiG2RvQ/jX2I4iVc=-OI15BYt5lqzGKY9qETxgcCU5z6qXNy3qWrgA8Zjfi6k=]: dropping too big huge message: size=169980
[ 3][t 5][2024-06-19 13:51:04.680090203][download-state.cpp:195][!downloadstatereq(-1,8000000000000000,38454136)]       downloading state (-1,8000000000000000,38454136):C233838B0EBB7E72B8F7FA9FAADBC51291A907DEBA7A5FE6364C4F7EFF3E2511:3D4B8991348E99CFE1BCBEFA3AD31ADFF3BC435BF4ED2DAF4C837BF14EB2934D: total=1858076672 (3049KB/s)
[ 2][t 5][2024-06-19 13:51:08.303236071][full-node-shard.cpp:507][!manager]     getnextkey: [Error : 651 : not inited]
[ 2][t 4][2024-06-19 13:51:13.288369349][full-node-shard.cpp:507][!manager]     getnextkey: [Error : 651 : not inited]
[ 3][t 3][2024-06-19 13:51:14.712188619][download-state.cpp:195][!downloadstatereq(-1,8000000000000000,38454136)]       downloading state (-1,8000000000000000,38454136):C233838B0EBB7E72B8F7FA9FAADBC51291A907DEBA7A5FE6364C4F7EFF3E2511:3D4B8991348E99CFE1BCBEFA3AD31ADFF3BC435BF4ED2DAF4C837BF14EB2934D: total=1889533952 (3062KB/s)
[ 2][t 1][2024-06-19 13:51:18.153781267][full-node-shard.cpp:507][!manager]     getnextkey: [Error : 651 : not inited]
[ 3][t 5][2024-06-19 13:51:24.818094438][download-state.cpp:195][!downloadstatereq(-1,8000000000000000,38454136)]       downloading state (-1,8000000000000000,38454136):C233838B0EBB7E72B8F7FA9FAADBC51291A907DEBA7A5FE6364C4F7EFF3E2511:3D4B8991348E99CFE1BCBEFA3AD31ADFF3BC435BF4ED2DAF4C837BF14EB2934D: total=1920991232 (3039KB/s)
[ 3][t 2][2024-06-19 13:51:35.427898490][download-state.cpp:195][!downloadstatereq(-1,8000000000000000,38454136)]       downloading state (-1,8000000000000000,38454136):C233838B0EBB7E72B8F7FA9FAADBC51291A907DEBA7A5FE6364C4F7EFF3E2511:3D4B8991348E99CFE1BCBEFA3AD31ADFF3BC435BF4ED2DAF4C837BF14EB2934D: total=1954545664 (3088KB/s)
[ 2][t 5][2024-06-19 13:51:44.287430241][full-node-shard.cpp:507][!manager]     getnextkey: [Error : 651 : not inited]

**Comment by fmira21** [comment]
Hi @zhp1254 
Please try to apply the latest non-archive snapshot.
