### ISSUE TITLE
Mainnet configuration

### ISSUE THREAD

**Issue by 0x090909** [fmira21/ton-node-docker#5]
Hello I started the node but I get the following error after I set it up: 

<img width="1247" alt="Screenshot 2024-07-13 at 19 02 15" src="https://github.com/user-attachments/assets/b41b7d55-25c0-4f9d-b25e-8b1c17620629">

My env: 
<img width="728" alt="Screenshot 2024-07-13 at 19 02 38" src="https://github.com/user-attachments/assets/883e6d74-a0b9-468c-a5f2-cb3b04344aa2">

Is this the correct config for mainnent?

**Comment by fmira21** [comment]
Hi @0x090909 
Yes, your config appears to be correct.
Looks like your node is not synced so far - and I can see your feature request as well. Let me proceed there.

**Comment by 0x090909** [comment]
thanks, how can I check the sync progress?

**Comment by fmira21** [comment]
You can call the `/getWorkerState` method and check the current height your node is on.

**Comment by 0x090909** [comment]
@fmira21  is it normal that even if I turn off the node but I keep the api on, the errror I get is the exact same as I posted in the first message? how can I check the connection is properly done between the node and the api interface?

**Comment by 0x090909** [comment]
Also with the method you provided I only get this: 

<img width="341" alt="Screenshot 2024-07-15 at 19 52 56" src="https://github.com/user-attachments/assets/d25c941b-a532-4b7f-8a6e-f497c0f2614e">

I think something is wrong in my configuration

**Comment by 0x090909** [comment]
@fmira21  can you help me?
