### ISSUE TITLE
Ability to setup dump from https://dump.ton.org/

### ISSUE THREAD

**Issue by 0x090909** [fmira21/ton-node-docker#6]
Hello, 

Would be nice to allow the user to download the dump in order to skip the whole syncronization phase.

**Comment by fmira21** [comment]
Hi @0x090909 
Yep, this is planned and will be done in the nearest future.
Please confirm if you resolved your previous issue with applying the latest snapshot for me to close it.

**Comment by 0x090909** [comment]
@fmira21  I managed to do it myself, just downloaded the dump and executed again bootstrap and the init.sh script created the config from scratch again

**Comment by fmira21** [comment]
@0x090909 
Indeed, currently it's the only option.
My idea is to automate it a bit.
